In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [3]:
## Load the dataset
data = pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
# Preprocess the data
# Drop irrelevant features
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [5]:
# Encode categorical variable
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [8]:
## One hot encoder for geography column
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])

In [9]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [13]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [ ]:
## Combine one hot encoded col with original data
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)

KeyError: "['Geography'] not found in axis"

In [17]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [18]:
## save encoders and scaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [19]:
## Divide the dataset in independent and dependent features
X = data.drop('Exited',axis=1)
y = data['Exited']

## Split data into training and testing set
X_train, X_test , y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

## Scale these features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
## Save the scaler function too
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [21]:
## Data is finally ready to apply ANN into it
data

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 13 columns]

### ANN Implementation

In [22]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [23]:
(X_train.shape[1],)

(12,)

In [24]:
## Build our model
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ## First hidden layer connected with input layer
    Dense(32,activation='relu'), ## Hidden layer 2
    Dense(1,activation='sigmoid') ## Output layer
])

WARNING:tensorflow:From c:\Users\anike\OneDrive\Desktop\python ml course\projects\ann_classification_project_churn_modelling\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [26]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)

In [27]:
## Compile the model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [28]:
## Set up tensorboard
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
log_dir = "logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [31]:
## Set up early stopping 
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [32]:
## Train the model
history = model.fit(
    X_train,y_train, validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3309 - accuracy: 0.8626 - val_loss: 0.3439 - val_accuracy: 0.8650
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3307 - accuracy: 0.8644 - val_loss: 0.3490 - val_accuracy: 0.8640
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3302 - accuracy: 0.8658 - val_loss: 0.3437 - val_accuracy: 0.8555
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3253 - accuracy: 0.8660 - val_loss: 0.3448 - val_accuracy: 0.8615
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3274 - accuracy: 0.8669 - val_loss: 0.3442 - val_accuracy: 0.8640
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3220 - accuracy: 0.8683 - val_loss: 0.3453 - val_accuracy: 0.8600
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3235 - accuracy: 0.8676 - val_loss: 0.3496 - val_accuracy: 0.8585
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3198 - accuracy: 0.8702 - val_loss: 0.3410 - val_accuracy: 0.8630
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3173 - accuracy: 0.8698 - val_loss: 0.3470 - val_accuracy: 0.8635
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3143 - accuracy: 0.8704 - val_loss: 0.3623 - val_accuracy: 0.8560
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3153 - accuracy: 0.8717 - val_loss: 0.3534 - val_accuracy: 0.8605
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3164 - accuracy: 0.8714 - val_loss: 0.3564 - val_accuracy: 0.8550
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3109 - accuracy: 0.8701 - val_loss: 0.3712 - val_accuracy: 0.8555
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3096 - accuracy: 0.8752 - val_loss: 0.3557 - val_accuracy: 0.8575
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3048 - accuracy: 0.8767 - val_loss: 0.3601 - val_accuracy: 0.8545
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3041 - accuracy: 0.8741 - val_loss: 0.3488 - val_accuracy: 0.8630
Epoch 17/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3041 - accuracy: 0.8754 - val_loss: 0.3761 - val_accuracy: 0.8535
Epoch 18/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3009 - accuracy: 0.8767 - val_loss: 0.3701 - val_accuracy: 0.8565

In [33]:
model.save('model.h5')

c:\Users\anike\OneDrive\Desktop\python ml course\projects\ann_classification_project_churn_modelling\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [42]:
!pip install --upgrade setuptools
!pip install --upgrade tensorboard

Requirement already satisfied: setuptools in .\venv\Lib\site-packages (82.0.1)
Requirement already satisfied: tensorboard in .\venv\Lib\site-packages (2.20.0)
Requirement already satisfied: absl-py>=0.4 in .\venv\Lib\site-packages (from tensorboard) (2.4.0)
Requirement already satisfied: grpcio>=1.48.2 in .\venv\Lib\site-packages (from tensorboard) (1.81.1)
Requirement already satisfied: markdown>=2.6.8 in .\venv\Lib\site-packages (from tensorboard) (3.10.2)
Requirement already satisfied: numpy>=1.12.0 in .\venv\Lib\site-packages (from tensorboard) (1.26.4)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from tensorboard) (26.0)
Requirement already satisfied: pillow in .\venv\Lib\site-packages (from tensorboard) (12.2.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in .\venv\Lib\site-packages (from tensorboard) (4.25.9)
Requirement already satisfied: setuptools>=41.0.0 in .\venv\Lib\site-packages (from tensorboard) (82.0.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\venv\Lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv\Lib\site-packages (from tensorboard) (3.1.8)
Requirement already satisfied: typing-extensions~=4.12 in .\venv\Lib\site-packages (from grpcio>=1.48.2->tensorboard) (4.15.0)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv\Lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)

NameError: name 'pkg_resources' is not defined

In [ ]:
## Load Tensorboard extension

%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Requirement already satisfied: setuptools in .\venv\Lib\site-packages (82.0.1)
Requirement already satisfied: tensorboard in .\venv\Lib\site-packages (2.15.2)
Collecting tensorboard
  Using cached tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: absl-py>=0.4 in .\venv\Lib\site-packages (from tensorboard) (2.4.0)
Requirement already satisfied: grpcio>=1.48.2 in .\venv\Lib\site-packages (from tensorboard) (1.81.1)
Requirement already satisfied: markdown>=2.6.8 in .\venv\Lib\site-packages (from tensorboard) (3.10.2)
Requirement already satisfied: numpy>=1.12.0 in .\venv\Lib\site-packages (from tensorboard) (1.26.4)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from tensorboard) (26.0)
Requirement already satisfied: pillow in .\venv\Lib\site-packages (from tensorboard) (12.2.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in .\venv\Lib\site-packages (from tensorboard) (4.25.9)
Requirement already satisfied: setuptools>=41.0.0 in .\venv\Lib\site-packages (from tensorboard) (82.0.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\venv\Lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv\Lib\site-packages (from tensorboard) (3.1.8)
Requirement already satisfied: typing-extensions~=4.12 in .\venv\Lib\site-packages (from grpcio>=1.48.2->tensorboard) (4.15.0)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv\Lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Downloading tensorboard-2.20.0-py3-none-any.whl (5.5 MB)
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   ------- -------------------------------- 1.0/5.5 MB 5.6 MB/s eta 0:00:01
   ------------------ --------------------- 2.6/5.5 MB 6.6 MB/s eta 0:00:01
   ---------------------------- ----------- 3.9/5.5 MB 6.7 MB/s eta 0:00:01
   ---------------------------------------  5.5/5.5 MB 6.8 MB/s eta 0:00:01
   ---------------------------------------- 5.5/5.5 MB 6.7 MB/s  0:00:00
Installing collected packages: tensorboard
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.15.2
    Uninstalling tensorboard-2.15.2:
      Successfully uninstalled tensorboard-2.15.2
Successfully installed tensorboard-2.20.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.15.0 requires tensorboard<2.16,>=2.15, but you have tensorboard 2.20.0 which is incompatible.

In [41]:
%tensorboard --logdir logs/fit20260616-000506

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\anike\OneDrive\Desktop\python ml course\projects\ann_classification_project_churn_modelling\venv\Scripts\tensorboard.exe\__main__.py", line 2, in <module>
  File "C:\Users\anike\OneDrive\Desktop\python ml course\projects\ann_classification_project_churn_modelling\venv\Lib\site-packages\tensorboard\main.py", line 27, in <module>
    from tensorboard import default
  File "C:\Users\anike\OneDrive\Desktop\python ml course\projects\ann_classification_project_churn_modelling\venv\Lib\site-packages\tensorboard\default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'